# Generated by Django 3.2.8 on 2021-11-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Poet',
        ),
        migrations.RenameField(
            model_name='poet',
            old_name='question_text',
            new_name='title',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
