# Generated by Django 3.2.8 on 2021-11-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0002_auto_20211109_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poet',
            old_name='title',
            new_name='Name',
        ),
    ]
