# Generated by Django 3.2.8 on 2021-11-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp5', '0003_rename_title_poet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poem_name', models.CharField(max_length=128)),
                ('poet_name', models.CharField(max_length=128)),
                ('age', models.CharField(max_length=128)),
                ('poem', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Poet',
        ),
    ]
